// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogPostDocumentDataSlicesSlice =
  | VideoBlockSlice
  | TextBlockSlice
  | TocBlockSlice
  | QuoteBlockSlice
  | CtaBlockSlice
  | ImageBlockSlice
  | CalloutBlockSlice;

/**
 * Content for blog_post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *blog_post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the blog post title here
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Publication Date field in *blog_post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.publication_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  publication_date: prismic.DateField;

  /**
   * Author field in *blog_post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter author name
   * - **API ID Path**: blog_post.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Featured Image field in *blog_post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *blog_post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * SEO Title Field field in *blog_post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter SEO-optimized title (70 characters max)
   * - **API ID Path**: blog_post.seo_title_field
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  seo_title_field: prismic.KeyTextField;

  /**
   * Meta Description field in *blog_post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter meta description (150-160 characters recommended)
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image Field field in *blog_post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.og_image_field
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image_field: prismic.ImageField<never>;
}

/**
 * blog_post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = BlogPostDocument | PageDocument;

/**
 * Primary content in *CalloutBlock → Default → Primary*
 */
export interface CalloutBlockSliceDefaultPrimary {
  /**
   * variant field in *CalloutBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: info
   * - **API ID Path**: callout_block.default.primary.variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<
    "info" | "warning" | "success" | "error" | "tip" | "note",
    "filled"
  >;

  /**
   * title field in *CalloutBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *CalloutBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for CalloutBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalloutBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CalloutBlock*
 */
type CalloutBlockSliceVariation = CalloutBlockSliceDefault;

/**
 * CalloutBlock Shared Slice
 *
 * - **API ID**: `callout_block`
 * - **Description**: CalloutBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutBlockSlice = prismic.SharedSlice<
  "callout_block",
  CalloutBlockSliceVariation
>;

/**
 * Primary content in *CtaBlock → Default → Primary*
 */
export interface CtaBlockSliceDefaultPrimary {
  /**
   * headline field in *CtaBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headline: prismic.KeyTextField;

  /**
   * description field in *CtaBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * button_text field in *CtaBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button_link field in *CtaBlock → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_block.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * variant field in *CtaBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: primary
   * - **API ID Path**: cta_block.default.primary.variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<
    "primary" | "secondary" | "subtle" | "urgent" | "outline",
    "filled"
  >;

  /**
   * background_style field in *CtaBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: colored
   * - **API ID Path**: cta_block.default.primary.background_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  background_style: prismic.SelectField<
    "colored" | "bordered" | "minimal" | "gradient",
    "filled"
  >;

  /**
   * show_icon field in *CtaBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: cta_block.default.primary.show_icon
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_icon: prismic.BooleanField;

  /**
   * icon_type field in *CtaBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: arrow
   * - **API ID Path**: cta_block.default.primary.icon_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_type: prismic.SelectField<"arrow" | "download" | "external", "filled">;
}

/**
 * Default variation for CtaBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaBlock*
 */
type CtaBlockSliceVariation = CtaBlockSliceDefault;

/**
 * CtaBlock Shared Slice
 *
 * - **API ID**: `cta_block`
 * - **Description**: CtaBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaBlockSlice = prismic.SharedSlice<
  "cta_block",
  CtaBlockSliceVariation
>;

/**
 * Primary content in *ImageBlock → Default → Primary*
 */
export interface ImageBlockSliceDefaultPrimary {
  /**
   * image field in *ImageBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * caption field in *ImageBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_block.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;

  /**
   * full_width field in *ImageBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_block.default.primary.full_width
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  full_width: prismic.BooleanField;
}

/**
 * Default variation for ImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageBlock*
 */
type ImageBlockSliceVariation = ImageBlockSliceDefault;

/**
 * ImageBlock Shared Slice
 *
 * - **API ID**: `image_block`
 * - **Description**: ImageBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageBlockSlice = prismic.SharedSlice<
  "image_block",
  ImageBlockSliceVariation
>;

/**
 * Primary content in *QuoteBlock → Default → Primary*
 */
export interface QuoteBlockSliceDefaultPrimary {
  /**
   * quote_text field in *QuoteBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_block.default.primary.quote_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote_text: prismic.RichTextField;

  /**
   * author field in *QuoteBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_block.default.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * citation field in *QuoteBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_block.default.primary.citation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  citation: prismic.KeyTextField;
}

/**
 * Default variation for QuoteBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuoteBlock*
 */
type QuoteBlockSliceVariation = QuoteBlockSliceDefault;

/**
 * QuoteBlock Shared Slice
 *
 * - **API ID**: `quote_block`
 * - **Description**: QuoteBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteBlockSlice = prismic.SharedSlice<
  "quote_block",
  QuoteBlockSliceVariation
>;

/**
 * Primary content in *TextBlock → Default → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Content field in *TextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

/**
 * Item in *TocBlock → Default → Primary → sections*
 */
export interface TocBlockSliceDefaultPrimarySectionsItem {
  /**
   * section_title field in *TocBlock → Default → Primary → sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: toc_block.default.primary.sections[].section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * anchor_link field in *TocBlock → Default → Primary → sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: toc_block.default.primary.sections[].anchor_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  anchor_link: prismic.KeyTextField;
}

/**
 * Primary content in *TocBlock → Default → Primary*
 */
export interface TocBlockSliceDefaultPrimary {
  /**
   * title field in *TocBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: toc_block.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * estimated_read_time field in *TocBlock → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: toc_block.default.primary.estimated_read_time
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  estimated_read_time: prismic.NumberField;

  /**
   * show_progress field in *TocBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: toc_block.default.primary.show_progress
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_progress: prismic.BooleanField;

  /**
   * sections field in *TocBlock → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: toc_block.default.primary.sections[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sections: prismic.GroupField<
    Simplify<TocBlockSliceDefaultPrimarySectionsItem>
  >;
}

/**
 * Default variation for TocBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TocBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TocBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TocBlock*
 */
type TocBlockSliceVariation = TocBlockSliceDefault;

/**
 * TocBlock Shared Slice
 *
 * - **API ID**: `toc_block`
 * - **Description**: TocBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TocBlockSlice = prismic.SharedSlice<
  "toc_block",
  TocBlockSliceVariation
>;

/**
 * Primary content in *VideoBlock → Default → Primary*
 */
export interface VideoBlockSliceDefaultPrimary {
  /**
   * video_type field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: YouTube
   * - **API ID Path**: video_block.default.primary.video_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  video_type: prismic.SelectField<"YouTube" | "Vimeo" | "MP4", "filled">;

  /**
   * video_id  field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.video_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_id: prismic.KeyTextField;

  /**
   * caption field in *VideoBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_block.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Default variation for VideoBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoBlock*
 */
type VideoBlockSliceVariation = VideoBlockSliceDefault;

/**
 * VideoBlock Shared Slice
 *
 * - **API ID**: `video_block`
 * - **Description**: VideoBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoBlockSlice = prismic.SharedSlice<
  "video_block",
  VideoBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CalloutBlockSlice,
      CalloutBlockSliceDefaultPrimary,
      CalloutBlockSliceVariation,
      CalloutBlockSliceDefault,
      CtaBlockSlice,
      CtaBlockSliceDefaultPrimary,
      CtaBlockSliceVariation,
      CtaBlockSliceDefault,
      ImageBlockSlice,
      ImageBlockSliceDefaultPrimary,
      ImageBlockSliceVariation,
      ImageBlockSliceDefault,
      QuoteBlockSlice,
      QuoteBlockSliceDefaultPrimary,
      QuoteBlockSliceVariation,
      QuoteBlockSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TocBlockSlice,
      TocBlockSliceDefaultPrimarySectionsItem,
      TocBlockSliceDefaultPrimary,
      TocBlockSliceVariation,
      TocBlockSliceDefault,
      VideoBlockSlice,
      VideoBlockSliceDefaultPrimary,
      VideoBlockSliceVariation,
      VideoBlockSliceDefault,
    };
  }
}
