// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  callout_block: dynamic(() => import("./CalloutBlock")),
  cta_block: dynamic(() => import("./CtaBlock")),
  image_block: dynamic(() => import("./ImageBlock")),
  quote_block: dynamic(() => import("./QuoteBlock")),
  text_block: dynamic(() => import("./TextBlock")),
  toc_block: dynamic(() => import("./TocBlock")),
  video_block: dynamic(() => import("./VideoBlock")),
};
